sudo: false
language: python
cache: pip
install: pip install tox>=3.8.0
matrix:
  include:
    - env: ACTION=checkformatting
      python: '3.6'
      script:
        make checkformatting
    - env: ACTION=lint
      python: '2.7'
      script:
        make lint
    - env: ACTION=test
      python: '2.7'
      script:
        make test
